export const alcaldias = [
  'Azcapotzalco',
  'Miguel Hidalgo',
  'Cuauhtémoc',
  'Gustavo A. Madero',
  'Venustiano Carranza',
  'Iztacalco',
  'Benito Juárez',
  'Alvaro Obregón',
  'Coyoacán',
  'Cuajimalpa de Morelos',
  'Iztapalapa',
  'Magdalena Contreras',
  'Milpa Alta',
  'Tláhuac',
  'Tlalpan',
  'Xochimilco',
  'Otro',
];

export const escuelas = [
  'CECyT # 1 Gonzalo Vázquez Vela',
  'CECyT # 2 Miguel Bernard',
  'CECyT # 3 Estanislao Ramirez Ruíz',
  'CECyT # 4 Lázaro Cárdenas',
  'CECyT # 5 Benito Juárez',
  'CECyT # 6 Miguel Othón de Mendizábal',
  'CECyT # 7 Cuauhtémoc',
  'CECyT # 8 Narciso Bassols',
  'CECyT # 9 Juan de Dios Bátiz',
  'CECyT # 10 Carlos Vallejo Márquez',
  'CECyT # 11 Wilfrido Massieu',
  'CECyT # 12 José María Morelos',
  'CECyT # 13 Ricardo Flores Magón',
  'CECyT # 14 Luis Enrique Erro',
  'CECyT # 15 Diódoro Antúnez Echegaray',
  'CECyT # 16 Hidalgo',
  'CECyT # 17 León, Guanajuato',
  'CECyT # 18 Zacatecas',
  'CECyT # 19 Leona Vicario',
  'CET # 1 Walter Cross Buchanan',
  'Otro',
];

export const estados = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Estado de México',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
];

export const prioridad = ['Primera opción', 'Segunda opción', 'Tercera opción'];
